[en]
  title = "The Missing Lien"
  languageName = "English"
  weight = 1
  contentdir = "content/en"

[ko]
  title = "The Missing Lien"
  languageName = "한국어"
  weight = 2
  contentdir = "content/ko"
