title = "The Missing Lien: Community Documentation for Lien Finance"
theme = ["hugo-notice", "tract"]
baseURL = "https://vibrant-torvalds-ea10cc.netlify.app"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[taxonomies]
tag = "tags"

[params]
description = "The Missing Lien: Community Documentation for Lien Finance, a self-regulating protocol for creating unique derivative contracts."
icon_set = "ionicons"

[params.colors]
primary = "#880e4f"
secondary = "#1e88e5"

[markup.highlight]
style = "fruity"

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "Alata"
sizes = [400]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [400]
type = "monospace"

[params.social.twitter]
handle = "LienFinance"

[params.social.github]
repo = "tokenbrice/tml"

[params.social.telegram]
group = "test"

[[menu.main]]
name = "Docs"
identifier = "docs"
url = "/docs"
weight = 1

[[menu.main]]
name = "Lien Overview"
parent = "docs"
url = "/docs/overview"
weight = 1

[[menu.main]]
name = "iDOL Stablecoin"
parent = "docs"
url = "/docs/idol"
weight = 2

[[menu.main]]
name = "FairSwap"
parent = "docs"
url = "/docs/fairswap"
weight = 2

[languages.en]
languageName = "🇺🇸 English"
contentDir = "content/en"
weight = 1
title = "The Missing Lien"

[languages.en.params]
description = "Community Documentation for Lien Finance, a self-regulating protocol for creating unique derivative contracts."

[languages.fr]
languageName = "🇫🇷 Français"
contentDir = "content/fr"
weight = 1
title = "Le Lien Manquant"

[languages.fr.params]
description = "Documentation communautaire pour le projet Lien Finance, un protocol auto-régulé pour générer des contracts dérivés sur Ethereum."